INCLUDE IRVINE32.inc
.data
msg1 byte 0AH, "### WELCOME TO LIBRARY MANAGEMENT SYSTEM ###", 0dh, 0ah, 0ah,
		"Choose One of the Following Options:", 0dh, 0ah,
		"1: Register a Member", 0dh, 0ah,
		"2: Unregister a Member", 0dh, 0ah,
		"3: View Members", 0dh, 0ah,
		"4: Add Book", 0dh, 0ah,
		"5: Remove Book", 0dh, 0ah,
		"6: View Books", 0dh, 0ah,
		"7: Exit Program", 0dh, 0ah, 0
REG_MSG BYTE "Enter Member's Name to register: ",0
UNREG_MSG BYTE "Enter Member's Name to unregister: ",0
VIEW_MEMBERS_MSG BYTE "Viewing Registered Members: ",0
ADD_MSG BYTE "Enter Book Name to Add: ",0
REMOVE_MSG BYTE "Enter Book Name to Remove: ",0
VIEW_BOOKS_MSG BYTE "Viewing Books in Library: ",0
EXIT_MSG BYTE "Exiting Program...",0dh, 0ah,
				"See you again :')", 0


REGISTER DWORD 1
UNREGISTER DWORD 2
VIEW_MEMBERS DWORD 3
ADD_BOOK DWORD 4
REMOVE_BOOK DWORD 5
VIEW_BOOKS DWORD 6
EXITP DWORD 7	
.code
MSG_DISPLAY proto, var: ptr dword
main proc
	START:
	INVOKE MSG_DISPLAY,addr MSG1
	CALL READINT

	CMP EAX, REGISTER
	JE REG_M
	CMP EAX, UNREGISTER
	JE UNREG_M
	CMP EAX, VIEW_MEMBERS
	JE VIEW_M
	CMP EAX, ADD_BOOK
	JE ADD_B
	CMP EAX, REMOVE_BOOK
	JE REMOVE_B
	CMP EAX, VIEW_BOOKS
	JE VIEW_B
		JMP EXIT_MENU
	REG_M:
		INVOKE MSG_DISPLAY, ADDR REG_MSG
		CALL READSTRING
		CALL WRITESTRING
		JMP START
	UNREG_M:
		INVOKE MSG_DISPLAY, ADDR UNREG_MSG
		CALL READSTRING
		CALL WRITESTRING
		JMP START
		
	VIEW_M:
		INVOKE MSG_DISPLAY, ADDR VIEW_MEMBERS_MSG

		JMP START
		
	ADD_B:
		INVOKE MSG_DISPLAY, ADDR ADD_MSG
		CALL READSTRING
		CALL WRITESTRING
		JMP START

	REMOVE_B:
		INVOKE MSG_DISPLAY, ADDR REMOVE_MSG
		CALL READSTRING
		CALL WRITESTRING
		JMP START

	VIEW_B:
		INVOKE MSG_DISPLAY, ADDR VIEW_BOOKS_MSG

		JMP START

	EXIT_MENU:
		INVOKE MSG_DISPLAY, ADDR EXIT_MSG
	
	invoke ExitProcess,0
main endp
MSG_DISPLAY PROC USES EDX, VAR: ptr dword
	MOV EDX, VAR
	CALL WRITESTRING
	RET
	MSG_DISPLAY ENDP
end main